name: learn-github-actions
on: [push]
permissions:
  contents: write
jobs:
  linux-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.7
      - run: crystal build test.cr -o Test --release
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./Test